name: devTestingWorkflow

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: ./ui
        run: npm install
      - name: Build app
        working-directory: ./ui
        run: npm run build --if-present
      - name: Test app
        working-directory: ./ui
        run: npm test
